import { TokenTypes } from './TokenTypes';

export enum TextToToken{
    "for" = TokenTypes.ForKeyword,
    "break" = TokenTypes.BreakKeyword,
    "while" = TokenTypes.WhileKeyword,
    "else" = TokenTypes.ElseKeyword,
    "elseif" = TokenTypes.ElseIfKeyword,
    "if" = TokenTypes.IfKeyword,
    "return" = TokenTypes.ReturnKeyword,
    "int" = TokenTypes.IntKeyword,
    "double" = TokenTypes.DoubleKeyword,
    "-" = TokenTypes.MinusToken,
    "--" = TokenTypes.MinusMinusToken,
    "+" = TokenTypes.PlusToken,
    "++" = TokenTypes.PlusPlusToken,
    "*" = TokenTypes.AsteriskToken,
    "/" = TokenTypes.SlashToken,
    "%" = TokenTypes.PercentToken,
    "!" = TokenTypes.ExclamationToken,
    "&&" = TokenTypes.AmpersandAmpersandToken,
    "||" = TokenTypes.BarBarToken,
    "==" = TokenTypes.EqualsEqualsToken, 
    "=" = TokenTypes.EqualsToken,
    "!=" = TokenTypes.ExclamationEqualsToken,
    ">" = TokenTypes.GreaterThanToken,
    "<" = TokenTypes.LessThanToken,
    ">=" = TokenTypes.GreaterThanEqualsToken,
    "<=" = TokenTypes.LessThanEqualsToken,
    "{" = TokenTypes.OpenBraceToken,
    "}" = TokenTypes.CloseBraceToken,
    "(" = TokenTypes.OpenParenToken,
    ")" = TokenTypes.CloseParenToken,
    "." = TokenTypes.DotToken,
    ":" = TokenTypes.ColonToken,
    ";" = TokenTypes.SemicolonToken,
    "," = TokenTypes.CommaToken,
    " " = TokenTypes.WhiteSpace,
}